module.exports = {
    rules: {
        'array-bracket-newline': ['error', { multiline: true }],
        'array-bracket-spacing': ['error', 'never'],
        'array-element-newline': ['error', { multiline: true }],
        'block-spacing': ['error', 'always'],
        'brace-style': ['error', '1tbs', { allowSingleLine: false }],
        camelcase: ['error', { properties: 'always', ignoreDestructuring: false }],
        'capitalized-comments': 'off',
        'comma-dangle': ['error', 'always-multiline'],
        'comma-spacing': ['error', { before: false, after: true }],
        'comma-style': ['error', 'last'],
        'computed-property-spacing': ['error', 'never'],
        'consistent-this': 'error',
        'eol-last': ['error', 'always'],
        'func-call-spacing': ['error', 'never'],
        'func-name-matching': ['off'],
        'func-names': ['warn', 'as-needed'],
        'func-style': 'warn',
        'function-paren-newline': ['error', 'multiline'],
        'id-blacklist': 'off',
        'id-length': 'off',
        'id-match': 'off',
        'implicit-arrow-linebreak': ['error', 'beside'],
        'indent': ['error', 4],
        'jsx-quotes': ['error', 'prefer-double'],
        'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
        'keyword-spacing': ['error', { before: true, after: true }],
        'line-comment-position': 'off',
        'linebreak-style': ['error', 'unix'],
        'lines-around-comment': ['error', { beforeBlockComment: true, beforeLineComment: true }],
        'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: false }],
        'max-depth': ['warn', 5],
        'max-len': ['error', 100, 2, {
            ignoreUrls: true,
            ignoreComments: false,
            ignoreRegExpLiterals: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
        }],
        'max-lines': 'off',
        'max-lines-per-function': 'off',
        'max-nested-callbacks': ['warn', 5],
        'max-params': 'off',
        'max-statements': 'off',
        'max-statements-per-line': ['error', { max: 1 }],
        'multiline-comment-style': ['error', 'starred-block'],
        'multiline-ternary': ['error', 'always-multiline'],
        'new-cap': ['error', { newIsCap: true, capIsNew: false }],
        'new-parens': ['error', 'always'],
        'newline-per-chained-call': ['error', { ignoreChainWithDepth: 1 }],
        'no-array-constructor': 'error',
        'no-bitwise': 'warn',
        'no-continue': 'off',
        'no-inline-comments': 'off',
        'no-lonely-if': 'error',
        'no-mixed-operators': 'error',
        'no-mixed-spaces-and-tabs': 'error',
        'no-multi-assign': 'error',
        'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 1 }],
        'no-negated-condition': 'error',
        'no-nested-ternary': 'error',
        'no-new-object': 'error',
        'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
        'no-restricted-syntax': 'off',
        'no-tabs': 'off',
        'no-ternary': 'off',
        'no-trailing-spaces': 'off',
        'no-underscore-dangle': 'off',
        'no-unneeded-ternary': 'error',
        'no-whitespace-before-property': 'error',
        'nonblock-statement-body-position': 'off',
        'object-curly-newline': ['error', { multiline: true }],
        'object-curly-spacing': ['error', 'never'],
        'object-property-newline': ['error', { allowAllPropertiesOnSameLine: false }],
    },
};
